

class TransactionPool:
  def __init__(self):
    self.transaction_map = {}
    
  def add_transaction(self, transaction):
    """
    Add a transaction in the transaction pool
    """
    self.transaction_map[transaction.id] = transaction

  def existing_transaction(self, address):
    """
    find a transaction generated by the address in the transaction pool
    """
    for transaction in self.transaction_map.values():
      if transaction.input['address'] == address:
        return transaction